version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodeapp
    environment:
      - MONGO_URI=mongodb://mongo_db/nodeapp
    ports:
      - "80:3000"
    networks:
      nodemernapp:
  db:
    image: mongo:3.0.15
    volumes:
      - mongo-db:/data/db
    networks:
      nodemernapp:
        aliases:
          - "mongo_db"

networks:
  nodemernapp:
    driver: bridge

volumes:
  mongo-db:

